# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d09bef181e97efceeaa613ed8c22be45048ae59bd31b57821f7b8bf6eb74b2613774b50fa8067c73d6ed053ef6f48da327d75964ec0ac39cce0759d6b24a965

test:
  secret_key_base: be21b72a16ba4689306d41ea1b38e675aea3d2d189bef9bfd9cf138dcc6dccbceb2eebc11e6c6f39d6c995d6341a0fa3909726c4b038e52a59837e0113be39ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
